image: node:16-alpine

cache:
  key: ${CI_COMMIT_REF_SLUG} # per branch
  paths:
    - .npm/
    - node_modules

stages:
  - Install
  - Testing
  - Release
  - Build

Dependencies:
  stage: Install
  interruptible: true
  script:
    - npm ci

Lint:
  stage: Testing
  needs: [Dependencies]
  interruptible: true
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run lint:eslint
    - npm run lint:prettier

Test:
  stage: Testing
  needs: [Dependencies]
  interruptible: true
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run test
  artifacts:
    when: always
    paths:
      - coverage
    expire_in: 1 days

Build Android:
  stage: Build
  image: reactnativecommunity/react-native-android:latest
  only:
    - main
  script:
    - npm ci --cache .npm --prefer-offline
    - npm run android:release
  artifacts:
    paths:
      - android/app/build/outputs/apk/release/app-release.apk
    expire_in: 7 days
