name: Build & Release

on:
  repository_dispatch:
    types: [Build & Release]

jobs:
  build-create-release:
    name: Build & Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    container:
      image: reactnativecommunity/react-native-android:latest
      options: --user 1001
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Build Android
        id: build_android
        run: |
          npm ci
          npm run android:release
          ls -al android/app/build/outputs/apk/release/app-release.apk

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          tag_name: ${{ github.event.client_payload.ref }}
          name: '<Update release name for ${{ github.event.client_payload.ref }}>'
          draft: true
          prerelease: false
          files: android/app/build/outputs/apk/release/app-release.apk
