name: Build & Release

on:
  repository_dispatch:
    types: [Build & Release]

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    container:
      image: reactnativecommunity/react-native-android:latest
      options: --user 1001
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Build Android
        run: |
          npm run android:release
          mv android/app/build/outputs/apk/release/app-release.apk android-release.apk

      - name: Archive Android APK file
        uses: actions/upload-artifact@v3
        with:
          name: android
          path: android-release.apk

  build-ios:
    name: Build iOS
    runs-on: macos-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Setup node version
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Install pod dependencies
        working-directory: ios
        run: pod install

      - name: Build iOS
        run: |
          npm run ios:build
          cp -R $HOME/Library/Developer/Xcode/DerivedData/ReactNativeBoilerplate-*/Build/Products/Release-iphonesimulator/*.app iOS-release.app

      - name: Archive iOS app file
        uses: actions/upload-artifact@v3
        with:
          name: iOS
          path: iOS-release.app

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build-android, build-ios]
    permissions:
      contents: write
      packages: write
    steps:
      - name: Download all workflow run artifacts
        uses: actions/download-artifact@v3

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          tag_name: ${{ github.event.client_payload.ref }}
          name: '<Update release name for ${{ github.event.client_payload.ref }}>'
          draft: true
          prerelease: false
          files: |
            android/android-release.apk
            iOS/iOS-release.app
